### ISSUE TITLE
А почему нет приложения в Windows Store?

### ISSUE THREAD

**Issue by sovaz1997** [eadordzhiev/DjvuApp#21]
Здравствуйте! А почему нет приложения в Windows Store?

**Comment by eadordzhiev** [comment]
Привет! MS удалило его из Store из-за отсутствия ссылки на Privacy Policy. Это не сложно исправить, но у меня сейчас дома отсутствует интернет. Как только он появится, сразу же выложу обратно в Store.

**Comment by sovaz1997** [comment]
Хорошо. Спасибо!
